### ISSUE TITLE
IEEE Format Double Sided Paper Draft

### ISSUE THREAD

**Issue by Avishek8136** [Avishek8136/Algorithmic-Symphony#2]

**Comment by Avishek8136** [comment]
IEEE reference Papers:

 https://www.sciencedirect.com/science/article/pii/S0957417424008571

**Comment by Avishek8136** [comment]
These are amrita affiliations

**Comment by Avishek8136** [comment]
https://link.springer.com/chapter/10.1007/978-981-99-9489-2_36

**Comment by Avishek8136** [comment]
https://ieeexplore.ieee.org/document/5580488/

https://ieeexplore.ieee.org/document/5550056

**Comment by Avishek8136** [comment]
https://link.springer.com/content/pdf/10.1007/s10772-024-10095-8.pdf

**Comment by Avishek8136** [comment]
https://link.springer.com/chapter/10.1007/978-981-97-2079-8_30

**Comment by Avishek8136** [comment]
https://www.sciencedirect.com/science/article/pii/S0045790624000260

**Comment by Avishek8136** [comment]
https://[link.springer.com/content/pdf/10.1007/s11042-023-16519-y.pdf](https://link.springer.com/content/pdf/10.1007/s11042-023-16519-y.pdf)

**Comment by Avishek8136** [comment]
The above all are Amrita Citations

**Comment by Avishek8136** [comment]
From Here Non Amrita Affilations Starts: 

https://www.sciencedirect.com/science/article/pii/S2666990023000150

**Comment by Avishek8136** [comment]
https://www.sciencedirect.com/science/article/pii/S0031320321001758

https://ieeexplore.ieee.org/abstract/document/4811455

https://www.sciencedirect.com/science/article/pii/S156849462030329X

**Comment by Avishek8136** [comment]
https://www.sciencedirect.com/science/article/pii/S0141933121004579

https://ieeexplore.ieee.org/abstract/document/9632912

**Comment by Avishek8136** [comment]
https://www.mdpi.com/2227-7390/8/10/1814

**Comment by quark365** [comment]
Hi

**Comment by Avishek8136** [comment]
2 amrita citations included namely 1 and 2

**Comment by Avishek8136** [comment]
one more in 7

**Comment by Avishek8136** [comment]
Completed Draft for now.
